attractions = [
    {
        "name": "Pyramids of Giza",
        "city": "Giza",
        "location_latitude": 29.9792,
        "location_longitude": 31.1342,
        "summary": "Ancient pyramids of pharaohs",
        "description": "The Pyramids of Giza are one of the most famous and iconic attractions in Egypt. They include the Great Pyramid of Khufu, the Pyramid of Khafre, and the Pyramid of Menkaure, as well as the iconic Sphinx.",
        "image": "https://i.natgeofe.com/n/535f3cba-f8bb-4df2-b0c5-aaca16e9ff31/giza-plateau-pyramids.jpg",
    },
    {
        "name": "The Sphinx",
        "city": "Giza",
        "location_latitude": 29.9753,
        "location_longitude": 31.1377,
        "summary": "Monumental statue of a mythical creature",
        "description": "The Sphinx is a large limestone statue with the body of a lion and the head of a human, believed to represent the Pharaoh Khafre. It is located on the Giza Plateau, near the Pyramids of Giza.",
        "image": "https://cdn.britannica.com/85/99185-050-E1110E5C/Great-Sphinx-Giza-Egypt.jpg",
    },
    {
        "name": "Karnak Temple Complex",
        "city": "Luxor",
        "location_latitude": 25.7188,
        "location_longitude": 32.6573,
        "summary": "Ancient temple complex",
        "description": "The Karnak Temple Complex is a vast open-air museum in Luxor, dedicated to the ancient god Amun. It is a significant religious site and one of the largest temple complexes in the world.",
        "image": "https://cdn.mos.cms.futurecdn.net/5HrnHp9ybAqYrtruKAsfkN.jpg",
    },
    {
        "name": "Valley of the Kings",
        "city": "Luxor",
        "location_latitude": 25.7403,
        "location_longitude": 32.6013,
        "summary": "Royal burial site",
        "description": "The Valley of the Kings is a burial ground for pharaohs and powerful nobles of the New Kingdom. It contains numerous tombs, including the famous tomb of Tutankhamun.",
        "image": "https://lp-cms-production.imgix.net/2023-07/f6e18c09be072890091813ba173e0fae-valley-of-the-kings.jpeg",
    },
    {
        "name": "Abu Simbel Temples",
        "city": "Aswan",
        "location_latitude": 22.3367,
        "location_longitude": 31.6253,
        "summary": "Ancient temples relocated to higher ground",
        "description": "The Abu Simbel Temples are two massive rock temples built by Pharaoh Ramses II in Nubia. They were relocated to higher ground during the construction of the Aswan High Dam.",
        "image": "https://cdn.britannica.com/49/189749-050-EDADDEC0/Great-Temple-of-Ramses-II-temples-larger.jpg",
    },
    {
        "name": "Egyptian Museum",
        "city": "Cairo",
        "location_latitude": 30.0476,
        "location_longitude": 31.2336,
        "summary": "Museum of ancient Egyptian antiquities",
        "description": "The Egyptian Museum in Cairo is home to an extensive collection of ancient Egyptian antiquities, including the treasures of Tutankhamun and other pharaohs.",
        "image": "https://upload.wikimedia.org/wikipedia/commons/7/71/The_Egyptian_Museum.jpg",
    },
    {
        "name": "Luxor Temple",
        "city": "Luxor",
        "location_latitude": 25.6998,
        "location_longitude": 32.6393,
        "summary": "Ancient temple dedicated to Theban Triad",
        "description": "The Luxor Temple is a large ancient temple complex dedicated to the Theban Triad of Amun, Mut, and Chons. It is beautifully illuminated at night and is a popular tourist attraction.",
        "image": "https://i0.wp.com/the-past.com/wp-content/uploads/2021/12/post-1_image0-14.jpg?ssl=1",
    },
    {
        "name": "Philae Temple",
        "city": "Aswan",
        "location_latitude": 24.0256,
        "location_longitude": 32.8847,
        "summary": "Island temple dedicated to goddess Isis",
        "description": "The Philae Temple is an island temple dedicated to the goddess Isis. It was rescued from being submerged by the rising waters of the Nile and relocated to Agilkia Island.",
        "image": "https://media.tacdn.com/media/attractions-splice-spp-674x446/0b/df/cd/03.jpg",
    },
    {
        "name": "Saqqara",
        "city": "Cairo",
        "location_latitude": 29.8719,
        "location_longitude": 31.2165,
        "summary": "Ancient burial ground and pyramid complex",
        "description": "Saqqara is an ancient burial ground in Egypt, featuring numerous pyramids, including the Step Pyramid of Djoser, which is considered one of the earliest large stone structures.",
        "image": "https://www.civitatis.com/f/egipto/egipto/guia/saqqara.jpg",
    },
    {
        "name": "Aswan High Dam",
        "city": "Aswan",
        "location_latitude": 23.9642,
        "location_longitude": 32.8801,
        "summary": "Engineering marvel and hydroelectric dam",
        "description": "The Aswan High Dam is a major engineering project that controls the flow of the Nile River and provides hydroelectric power. It also led to the creation of Lake Nasser, one of the world's largest artificial lakes.",
        "image": "https://cdn.britannica.com/34/76234-050-6176AC39/Aswan-High-Dam-Egypt.jpg",
    },
    {
        "name": "Temple of Hatshepsut",
        "city": "Luxor",
        "location_latitude": 25.7374,
        "location_longitude": 32.6011,
        "summary": "Mortuary temple of the female pharaoh Hatshepsut",
        "description": "The Temple of Hatshepsut is a mortuary temple dedicated to the female pharaoh Hatshepsut. It is located on the west bank of the Nile near the Valley of the Kings.",
        "image": "https://www.worldhistory.org/img/c/p/1200x627/187.jpg",
    },
    {
        "name": "Colossi of Memnon",
        "city": "Luxor",
        "location_latitude": 25.7217,
        "location_longitude": 32.6106,
        "summary": "Gigantic twin statues of Amenhotep III",
        "description": "The Colossi of Memnon are two massive stone statues of Pharaoh Amenhotep III. They are some of the most recognizable monuments in Luxor and have been standing for millennia.",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Colossi_of_Memnon_May_2015_2.JPG/1200px-Colossi_of_Memnon_May_2015_2.JPG",
    },
    {
        "name": "Edfu Temple",
        "city": "Aswan",
        "location_latitude": 24.9772,
        "location_longitude": 32.8746,
        "summary": "Well-preserved Ptolemaic temple",
        "description": "The Edfu Temple is a well-preserved ancient temple dedicated to the falcon god Horus. It is one of the best examples of Ptolemaic temple architecture in Egypt.",
        "image": "https://upload.wikimedia.org/wikipedia/commons/7/7f/Temple_Edfou_Egypte.jpg",
    },
    {
        "name": "Kom Ombo Temple",
        "city": "Aswan",
        "location_latitude": 24.4521,
        "location_longitude": 32.9361,
        "summary": "Unusual double temple dedicated to Sobek and Horus",
        "description": "The Kom Ombo Temple is an unusual double temple dedicated to two gods: Sobek, the crocodile god, and Horus, the falcon god. The temple offers insights into ancient religious beliefs.",
        "image": "https://egypttravelblog.com/wp-content/uploads/2021/02/Kom-Ombo-Temple-Shutterstock-copy.jpg",
    },
    {
        "name": "Hurghada",
        "city": "Red Sea",
        "location_latitude": 27.2579,
        "location_longitude": 33.8116,
        "summary": "Popular beach resort town",
        "description": "Hurghada is a popular tourist destination on the Red Sea coast, known for its beautiful beaches, crystal-clear waters, and vibrant coral reefs, making it a haven for snorkelers and divers.",
        "image": "https://static.independent.co.uk/2022/12/01/10/iStock-175210186.jpg",
    },
    {
        "name": "Dahab",
        "city": "Sinai Peninsula",
        "location_latitude": 28.5091,
        "location_longitude": 34.5136,
        "summary": "Laid-back coastal town and diving destination",
        "description": "Dahab is a relaxed coastal town on the Sinai Peninsula, famous for its laid-back atmosphere and excellent diving and snorkeling opportunities, including the famous Blue Hole.",
        "image": "https://i0.wp.com/tayaramuse.com/wp-content/uploads/2018/06/Dahab_Egypt-42.jpg?fit=2000%2C1333&ssl=1",
    },
    {
        "name": "White Desert",
        "city": "Farafra",
        "location_latitude": 27.2219,
        "location_longitude": 28.9142,
        "summary": "Unique desert landscape with white chalk formations",
        "description": "The White Desert is a surreal landscape of white chalk rock formations, shaped by the wind into whimsical shapes. It is a popular destination for adventurous desert safaris.",
        "image": "https://www.inside-egypt.com/img/thumbs/w1200h800q85/news/48ad90f964fde5c40c45.jpeg",
    },
    {
        "name": "Siwa Oasis",
        "city": "Matrouh",
        "location_latitude": 29.2039,
        "location_longitude": 25.5193,
        "summary": "Idyllic oasis town in the Western Desert",
        "description": "The Siwa Oasis is a remote and picturesque oasis town in the Western Desert of Egypt. It is known for its unique culture, ancient ruins, and beautiful natural springs.",
        "image": "https://venturetheplanet.com/wp-content/uploads/2021/09/DSC_9369-2.jpg",
    },
    {
        "name": "Mount Sinai",
        "city": "Sinai Peninsula",
        "location_latitude": 28.5391,
        "location_longitude": 33.9759,
        "summary": "Sacred mountain with religious significance",
        "description": "Mount Sinai, also known as Jebel Musa, is a sacred mountain in the Sinai Peninsula, revered in Christianity, Islam, and Judaism as the place where Moses received the Ten Commandments.",
        "image": "https://upload.wikimedia.org/wikipedia/commons/e/e6/Mount_Moses.jpg",
    },
    {
        "name": "Cairo Tower",
        "city": "Cairo",
        "location_latitude": 30.045,
        "location_longitude": 31.2244,
        "summary": "Iconic tower with panoramic views of Cairo",
        "description": "The Cairo Tower is a prominent landmark in the city and offers breathtaking panoramic views of Cairo and the surrounding areas from its observation deck.",
        "image": "https://www.egypttoursportal.com/images/2021/04/Cairo-Tower-Egypt-Tours-Portal-1.jpg",
    },
    {
        "name": "Alexandria Library",
        "city": "Alexandria",
        "location_latitude": 31.2089,
        "location_longitude": 29.9093,
        "summary": "Modern library honoring the ancient Library of Alexandria",
        "description": "The Alexandria Library, also known as the Bibliotheca Alexandrina, is a modern library and cultural center built to commemorate the ancient Library of Alexandria. It is a symbol of the city's intellectual and cultural heritage.",
        "image": "https://www.egypttoursportal.com/images/2017/11/Alexandria-Library-Egypt-Tours-Portal.jpg",
    },
    {
        "name": "Saint Catherine's Monastery",
        "city": "Sinai Peninsula",
        "location_latitude": 28.5545,
        "location_longitude": 33.9753,
        "summary": "Ancient monastery at the foot of Mount Sinai",
        "description": "Saint Catherine's Monastery is a historic Christian monastery situated at the foot of Mount Sinai. It is one of the oldest working monasteries in the world and holds significant religious and historical importance.",
        "image": "https://cdn.britannica.com/51/126951-050-19056A6C/St-Catherines-Monastery-Mount-Sinai-Egypt.jpg",
    },
    {
        "name": "Wadi Rum",
        "city": "Sinai Peninsula",
        "location_latitude": 29.5735,
        "location_longitude": 35.4216,
        "summary": "Scenic desert valley known as the Valley of the Moon",
        "description": "Wadi Rum, also known as the Valley of the Moon, is a striking desert valley known for its dramatic sandstone mountains, ancient petroglyphs, and unique landscapes. It is a popular destination for desert treks and adventure seekers.",
        "image": "https://www.deccanherald.com/sites/dh/files/styles/article_detail/public/article_images/2018/09/21/file70wmqwqk60917anc56a8.jpg?itok=GCISQPxF",
    },
    {
        "name": "Ras Mohammed National Park",
        "city": "Sinai Peninsula",
        "location_latitude": 27.9083,
        "location_longitude": 34.2885,
        "summary": "Diverse marine and terrestrial protected area",
        "description": "Ras Mohammed National Park is a protected area at the southern tip of the Sinai Peninsula. It boasts stunning coral reefs, diverse marine life, and unique geological formations, making it a paradise for snorkelers and divers.",
        "image": "https://media.tacdn.com/media/attractions-splice-spp-674x446/0b/df/bd/79.jpg",
    },
    {
        "name": "Al-Azhar Park",
        "city": "Cairo",
        "location_latitude": 30.046,
        "location_longitude": 31.261,
        "summary": "Beautiful urban park with historic significance",
        "description": "Al-Azhar Park is a green oasis in the heart of Cairo, offering beautiful gardens, historical sites, and panoramic views of the city. It was built on the site of the historic Fatimid-era city and is a popular recreational spot for locals and tourists alike.",
        "image": "https://upload.wikimedia.org/wikipedia/commons/9/91/Azhar_Park.jpg",
    },
    {
        "name": "Catacombs of Kom El Shoqafa",
        "city": "Alexandria",
        "location_latitude": 31.2095,
        "location_longitude": 29.9019,
        "summary": "Ancient Roman burial site",
        "description": "The Catacombs of Kom El Shoqafa are a series of ancient Roman tombs and burial chambers in Alexandria. They are a fascinating blend of Egyptian, Greek, and Roman architectural styles and provide insights into the multicultural history of the city.",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/CatacombsKomElShoqafa2.jpg/383px-CatacombsKomElShoqafa2.jpg",
    },
    {
        "name": "Dendera Temple Complex",
        "city": "Qena",
        "location_latitude": 26.1661,
        "location_longitude": 32.6457,
        "summary": "Ancient temple complex dedicated to Hathor",
        "description": "The Dendera Temple Complex is an ancient temple site dedicated to the goddess Hathor. It features well-preserved hieroglyphs, colorful reliefs, and an astronomical ceiling, providing valuable insights into ancient Egyptian religious beliefs.",
        "image": "https://www.egypttoursportal.com/images/2020/06/Dendera-Temple-Egypt-Tours-Portal.jpg",
    },
    {
        "name": "Temple of Horus",
        "city": "Edfu",
        "location_latitude": 24.9777,
        "location_longitude": 32.8759,
        "summary": "Impressive ancient temple dedicated to Horus",
        "description": "The Temple of Horus is a well-preserved ancient Egyptian temple dedicated to the falcon god Horus. It is located in the city of Edfu and is one of the most significant Ptolemaic temples in Egypt.",
        "image": "https://www.historyhit.com/app/uploads/2021/07/shutterstock_temple-of-horus-1.jpg",
    },
    {
        "name": "Valley of the Queens",
        "city": "Luxor",
        "location_latitude": 25.7304,
        "location_longitude": 32.5922,
        "summary": "Burial site of queens and royal children",
        "description": "The Valley of the Queens is a burial site in Luxor where queens and royal children from the New Kingdom were interred. It contains several beautifully decorated tombs, offering insights into ancient burial practices.",
        "image": "https://media.tacdn.com/media/attractions-splice-spp-674x446/0b/39/a4/be.jpg",
    },
    {
        "name": "Temple of Seti I",
        "city": "Abydos",
        "location_latitude": 26.1848,
        "location_longitude": 31.9193,
        "summary": "Ancient temple dedicated to pharaoh Seti I",
        "description": "The Temple of Seti I is an ancient Egyptian temple located in Abydos. It is dedicated to the pharaoh Seti I and showcases impressive reliefs and carvings depicting various religious and mythological scenes.",
        "image": "https://media.sketchfab.com/models/a4c7332781e74b669e923b51c22827f3/thumbnails/2a59c7d7361a41fdae764aaffe007788/cc54ab09acc44aa39056f82a04feec5b.jpeg",
    },
    {
        "name": "The Hanging Church",
        "city": "Cairo",
        "location_latitude": 30.0079,
        "location_longitude": 31.2308,
        "summary": "Historic Coptic Orthodox Church",
        "description": "The Hanging Church, also known as Saint Virgin Mary's Coptic Orthodox Church, is one of the oldest churches in Cairo. Its name comes from its location above the gatehouse of the ancient Roman fortress.",
        "image": "https://www.yallatours.com/blog/wp-content/uploads/2020/08/hanging-church-exterior.jpg",
    },
    {
        "name": "Qaitbay Citadel",
        "city": "Alexandria",
        "location_latitude": 31.214,
        "location_longitude": 29.8853,
        "summary": "15th-century defensive fortress",
        "description": "The Qaitbay Citadel is a historic fortress located on the Mediterranean coast in Alexandria. It was built in the 15th century on the site of the famous Lighthouse of Alexandria and served as a defensive stronghold.",
        "image": "https://www.traveltoegypt.net/front/images/blog/Citadel-Of-Qaitbay.jpg",
    },
    {
        "name": "Nubian Museum",
        "city": "Aswan",
        "location_latitude": 24.0805,
        "location_longitude": 32.8941,
        "summary": "Museum dedicated to Nubian culture and history",
        "description": "The Nubian Museum in Aswan showcases the culture, history, and heritage of the Nubian people. It houses a vast collection of artifacts and exhibits, providing visitors with insights into Nubian traditions and customs.",
        "image": "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1a/62/e3/55/caption.jpg?w=1200&h=-1&s=1",
    },
    {
        "name": "Cairo Opera House",
        "city": "Cairo",
        "location_latitude": 30.0438,
        "location_longitude": 31.2242,
        "summary": "Elegant performing arts venue",
        "description": "The Cairo Opera House is an elegant performing arts venue in Cairo, hosting a wide range of cultural events, including operas, ballets, concerts, and theatrical performances.",
        "image": "https://www.egypttoday.com/siteimages/Larg/77358.jpg",
    },
    {
        "name": "Dahshur",
        "city": "Cairo",
        "location_latitude": 29.7942,
        "location_longitude": 31.6616,
        "summary": "Archaeological site with ancient pyramids",
        "description": "Dahshur is an archaeological site in Cairo, known for its ancient pyramids, including the Bent Pyramid and the Red Pyramid, both built during the Old Kingdom of Egypt.",
        "image": "https://images.memphistours.com/large/f843d318dadb0008e50feb017c327b93.jpg",
    },
    {
        "name": "Baron Empain Palace",
        "city": "Cairo",
        "location_latitude": 30.0798,
        "location_longitude": 31.3365,
        "summary": "Distinctive Hindu and Cambodian-style palace",
        "description": "The Baron Empain Palace, located in Heliopolis, Cairo, is a unique mansion built by Belgian industrialist Edouard Empain. Its architecture is influenced by Hindu and Cambodian styles, making it a fascinating sight to explore.",
        "image": "https://www.egypttoursportal.com/images/2023/01/Baron-Empain-Palace-Egypt-Tours-Portal.jpg",
    },
    {
        "name": "El-Muizz Street",
        "city": "Cairo",
        "location_latitude": 30.047,
        "location_longitude": 31.2613,
        "summary": "Historic street with architectural treasures",
        "description": "El-Muizz Street, also known as Al-Muizz Street, is a historic thoroughfare in Cairo's Islamic Cairo district. It is lined with stunning architectural treasures, including mosques, madrasas, and old residences, reflecting centuries of history.",
        "image": "https://assets.cairo360.com/app/uploads/2018/05/1521457402hTzOS-1024x678.jpg",
    },
    {
        "name": "Gayer-Anderson Museum",
        "city": "Cairo",
        "location_latitude": 30.0459,
        "location_longitude": 31.2611,
        "summary": "Museum in a historic mansion with Islamic artifacts",
        "description": "The Gayer-Anderson Museum is housed in two historic mansions in Cairo's Islamic Cairo district. It showcases a remarkable collection of Islamic art, furniture, and artifacts, offering visitors a glimpse into the city's rich past.",
        "image": "https://www.ibisegypttours.com/images/Gayer-Anderson-Museum.jpg",
    },
    {
        "name": "Khan El Khalili",
        "city": "Cairo",
        "location_latitude": 30.0466,
        "location_longitude": 31.262,
        "summary": "Ancient bazaar and marketplace",
        "description": "Khan El Khalili is a famous bazaar and marketplace in Cairo's Islamic Cairo district. It is a bustling hub of activity, offering a wide range of goods, including spices, textiles, jewelry, and traditional crafts.",
        "image": "https://images.memphistours.com/large/1905250_Khan%20El%20Khalili%20market%20in%20Islamic%20Cairo.jpg",
    },
    {
        "name": "Nubian Village",
        "city": "Aswan",
        "location_latitude": 24.0898,
        "location_longitude": 32.8828,
        "summary": "Vibrant village showcasing Nubian culture",
        "description": "The Nubian Village in Aswan is a vibrant community on the banks of the Nile River. It offers an opportunity to experience Nubian culture, traditions, and hospitality, with colorful houses and friendly locals.",
        "image": "https://www.egypttoursportal.com/images/2019/09/Nubian-Village-Tour-From-Aswan-Egypt-Tours-Portal.jpg",
    },
    {
        "name": "Coptic Cairo",
        "city": "Cairo",
        "location_latitude": 30.0092,
        "location_longitude": 31.2313,
        "summary": "Historic area with Coptic Christian sites",
        "description": "Coptic Cairo is a historic neighborhood in Old Cairo, known for its significant Coptic Christian sites, including the Hanging Church, Coptic Museum, and Church of St. Sergius and Bacchus.",
        "image": "https://images.memphistours.com/large/3d9ae0f465b5e6d6c71a60e618f58eb0.jpg",
    },
    {
        "name": "Montaza Palace",
        "city": "Alexandria",
        "location_latitude": 31.288,
        "location_longitude": 30.0353,
        "summary": "Royal palace and gardens by the sea",
        "description": "Montaza Palace is a former royal palace located in Alexandria. It features beautiful gardens, impressive architecture, and stunning views of the Mediterranean Sea, making it a popular spot for locals and tourists to relax and enjoy the surroundings.",
        "image": "https://egyptianstreets.com/wp-content/uploads/2022/05/montaza-palace.jpeg",
    },
    {
        "name": "Temple of Medinet Habu",
        "city": "Luxor",
        "location_latitude": 25.7207,
        "location_longitude": 32.6021,
        "summary": "Massive temple complex in Thebes",
        "description": "The Temple of Medinet Habu is a vast temple complex on the west bank of the Nile in Luxor. It is dedicated to the god Amun and contains well-preserved reliefs, including battle scenes and religious ceremonies.",
        "image": "https://www.hurghadareisen.com/wp-content/uploads/2020/02/Medinet-Habu-Luxor-The-Mortuary-Temple-of-Ramses-III.-.jpeg",
    },
    {
        "name": "Tomb of Nefertari",
        "city": "Luxor",
        "location_latitude": 25.7405,
        "location_longitude": 32.6029,
        "summary": "Elaborately decorated tomb of Queen Nefertari",
        "description": "The Tomb of Nefertari is an elaborately decorated burial site of Queen Nefertari, one of the wives of Pharaoh Ramses II. It is renowned for its exquisite wall paintings and colorful scenes from ancient Egyptian mythology.",
        "image": "https://www.thediscoveriesof.com/wp-content/uploads/2022/06/Nefertari-Tomb-Luxor-7.jpg",
    }
]
